// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1hjLcZtMV3rbkkkBGhs4p6NrLPh0hAGk',
    appId: '1:170294570785:web:30df52b20975af7cdf1860',
    messagingSenderId: '170294570785',
    projectId: 'self-attendance-system',
    authDomain: 'self-attendance-system.firebaseapp.com',
    storageBucket: 'self-attendance-system.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtmPO0HJXenY7suR1OpuwepdAIQsslwvI',
    appId: '1:170294570785:android:1dcc0e2cfa0deac5df1860',
    messagingSenderId: '170294570785',
    projectId: 'self-attendance-system',
    storageBucket: 'self-attendance-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9B-X7Jxi0CcXtvqWVcQd0e_hOFKxiCzs',
    appId: '1:170294570785:ios:ebf0d36a020c2dc6df1860',
    messagingSenderId: '170294570785',
    projectId: 'self-attendance-system',
    storageBucket: 'self-attendance-system.firebasestorage.app',
    iosClientId: '170294570785-b8dkbal8im1sj7s4i3tk6q2e48qsejmv.apps.googleusercontent.com',
    iosBundleId: 'com.example.selfAttendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9B-X7Jxi0CcXtvqWVcQd0e_hOFKxiCzs',
    appId: '1:170294570785:ios:ebf0d36a020c2dc6df1860',
    messagingSenderId: '170294570785',
    projectId: 'self-attendance-system',
    storageBucket: 'self-attendance-system.firebasestorage.app',
    iosClientId: '170294570785-b8dkbal8im1sj7s4i3tk6q2e48qsejmv.apps.googleusercontent.com',
    iosBundleId: 'com.example.selfAttendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1hjLcZtMV3rbkkkBGhs4p6NrLPh0hAGk',
    appId: '1:170294570785:web:4a9c69f4649a8e65df1860',
    messagingSenderId: '170294570785',
    projectId: 'self-attendance-system',
    authDomain: 'self-attendance-system.firebaseapp.com',
    storageBucket: 'self-attendance-system.firebasestorage.app',
  );
}
